[book]
authors = ["Ethiraric"]
language = "en"
multilingual = false
src = "src"
title = "Ornabook"

[preprocessor.icons]
renderers = ["html"]

[output.html]
additional-css = ["./src/mdbook-icons.css"]
